### ISSUE TITLE
User.query AttributeError

### ISSUE THREAD

**Issue by kiddick** [jpscaletti/sqla-wrapper#29]
https://github.com/jpscaletti/sqla-wrapper/blob/master/docs/quickstart.rst#simple-relationships
Quickstart provides example:
```python
users = User.query.all()
```
but actually I am getting error:
`AttributeError: type object 'User' has no attribute 'query'`

**Comment by jpscaletti** [comment]
That's a bug. Sorry. It should be `db.query(User).all()`.
