### ISSUE TITLE
Two Pypi (pip) packages

### ISSUE THREAD

**Issue by ramuta** [jpscaletti/sqla-wrapper#31]
Hi!

There are two Pypi packages for this project:

- [SQLAlchemy-Wrapper](https://pypi.org/project/SQLAlchemy-Wrapper/)
- [sqla-wrapper](https://pypi.org/project/sqla-wrapper/)

The latter is probably the correct one (or the latest one), but having two pip packages can confuse users. Please either delete the `SQLAlchemy-Wrapper` package or add a notice in the README.md file to install `sqla-wrapper`.

Usually readme files start with installation instructions: `pip install sqla-wrapper`. This makes it clear which package to install.

**Comment by ramuta** [comment]
PR: https://github.com/jpscaletti/sqla-wrapper/pull/32

**Comment by jpscaletti** [comment]
PR merged. Thank you.
